[package]
name = "gdb-machine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
env_logger = "0.11.5"
gethostname = "0.5.0"
log = "0.4.22"
rayon = "1.10.0"
regex = "1.10.6"
serde = { version = "1.0.207", features = ["derive"] }
serde_json = "1.0.124"
